site_name: HTTPX Limiter
site_description: A lightweight package that provides rate-limited httpx transports.
site_author: Moritz E. Beber
site_url: https://httpx-limiter.readthedocs.io/

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme:
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - navigation.top
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_submodules: true
            show_if_no_docstring: true
            show_signature_annotations: true
            show_root_heading: true
            show_source: false
      default_handler: python
  - awesome-pages

extra:
  version:
    provider: mike
    default: stable
    alias: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Midnighter
      name: Moritz E. Beber

copyright: Copyright &copy 2024, 2025 Moritz E. Beber

repo_url: https://github.com/Midnighter/httpx-limiter
repo_name: Midnighter/httpx-limiter

watch:
  - src/httpx_limiter
